permissions:
  contents: write
  pull-requests: write

name: Download translations from Crowdin

on: workflow_dispatch

jobs:
  download-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install and Configure Python
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install python3-lxml python3-requests
        pip install crowdin-api-client --no-cache-dir

    - name: Download translations from Crowdin
      run: |
        python3 ./make_scripts/download_translations.py
      env:
        crowdin_project_id: ${{ vars.CROWDIN_PROJECT_ID }}
        crowdin_token: ${{ secrets.CROWDIN_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Import translation work from Crowdin
        title: New Crowdin translations
        branch: l10n_crowdin_action
        delete-branch: true
